import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import About from '../components/About/About'
import Projects from '../components/Projects/Projects'
import Skills from '../components/About/Skills'
import AboutDetails from '../components/About/AboutDetails'
import Blog from '../components/Blog/Blog'
import Contact from '../components/Contact/Contact'
import Navbar from '../components/Navbar/Navbar'

export default function Home() {
  return (
    <div >
      <Head>
        <title>Portfolio</title>
        <meta name="description" content="Generated by Portfolio" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar bgColor={"black"} />
      <About />
      <AboutDetails />
      <Projects />
      <Blog />
      <Contact />

    </div>
  )
}
